#!/usr/bin/python3
from src import gui
from sys import argv

a = argv[0]
for i in range(1, len(a)):
    if a[-i] == "/":
        daddyPath = a[0:len(a)-i]
        break
del a
configPath = f"{daddyPath}/data/config.json"
with open(configPath, 'r') as f:
    a = eval(f.read())
    wallheavenApi = a["wallheaven"][0]
    f.close()
del configPath

gui.main(daddyPath, wallheavenApi)
